### ISSUE TITLE
dbrt getting started doesn't work for kinetic

### ISSUE THREAD

**Issue by amichlee** [bayesian-object-tracking/getting_started#2]
Hey the dbrt_getting_started repo does not work for kinectic (I couldn't find a kinetic specific branch). You just need to change some of the urdf specifications. I created a separate repo for people who are using kinetic: https://github.com/amichlee/dbrt_getting_started

I can't access the MPI git so can't do a pull request. Hopefully someone can add this branch to the existing code.

**Comment by jbohg** [comment]
A new branch was created for dbrt_getting_started that works for 16.04 and kinetic. Installation Instructions are updated
